# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clase6Mod2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'JASidePanels', '~> 1.3'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  # Pods for Clase6Mod2

end
